Feature/header
Abrandrokc/Project-lazy-work pull request #5
Opened 2023-11-25 18:59 UTC by Vasyl-Djachuk

2023-11-25 22:22 UTC, Abrandrokc requested changes

2023-11-25 22:22 UTC, Abrandrokc commented on src/partials/header.html
> +  <div class="containe header-container section">
тут замість .containe повинен бути класс .container і тоді підключуться загальні стилі.

2023-11-26 08:10 UTC, Vasyl-Djachuk commented on src/partials/header.html
> +  <div class="containe header-container section">
я виправив, але в our collection прописаний container який перебиває, його треба переправити...

2023-11-26 08:59 UTC, Abrandrokc approved these changes

2023-11-26 09:04 UTC, merged